version: '3.8'

services:
  db:
    image: postgres:16
    container_name: mydb
    restart: always
    ports:
      - "5344:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
volumes:
  postgres-data:
